config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper scope: 'oauth'

  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq',constraints: AdminConstraint.new

  resources :sessions, only: [:new, :create, :destroy]
  resources :registrations, only: [:new, :create]

  root 'pages#home'

  get '/home' => 'pages#home'

  get 'oauth2/sign_in' => 'sessions#new', as: :oauth2_sign_in

  get 'sign_in' => 'sessions#new'
  get 'sign_in_fb' => 'sessions#create_with_fb'
  get 'sign_in_fb_m' => 'sessions#create_with_fb_m'

  get 'sign_up' => 'registrations#new'
  get 'sign_up_fb' => 'registrations#create_with_fb'
  get 'sign_up_fb_m' => 'registrations#create_with_fb_m'

  delete 'sign_out' => 'sessions#destroy'
  get '/forgot-password' => 'passwords#new', as: :forgot_password

  namespace :api do #, path: '/', constraints: {subdomain: 'api'} do
    namespace :v1 do
      get 'me' => 'credentials#me'
      resources :profiles
      resources :registrations, only: [:create]
    end
  end

  namespace :admin do
    root 'users#index'
    resources :users
  end

end

app/views/layouts/shared/_config.html.erb
<script>
  window.Config = {
    fbId: '<%= ENV["FB_ID"] %>',
    Flash: {
      key: '<%=flash_config[:key] %>',
      value: '<%= flash_config[:value] %>'
    }
  }
</script>

app/views/layouts/shared/_font.html.erb
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,900' rel='stylesheet' type='text/css'>

app/views/layouts/shared/_nav_bar.html.erb
<% if current_user %>
  <div>
    <%= link_to current_user.full_name, sign_out_path, method: :delete %>
  </div>
<% end %>

app/views/layouts/shared/_notification.html.erb
<div id='notification'></div>

<script id='tmpl-notification' type="text/x-tmpl">
  <div class="bs-callout bs-callout-{%=o.type%}">
    <h4>
      <span class='glyphicon glyphicon-{%=o.icon%}'> </span>
      {%=o.title%}
    </h4>
    
    <p>{%=o.body%}</p>
  </div>
</script>